name: basic tests

on:
  push:
    branches:
      - 'user/**'
      - 'feature/**'
      - 'improvement/**'
      - 'bugfix/**'
      - 'w/**'
      - 'q/**'
      - 'hotfix/**'
      - 'dependabot/**'
  pull_request:
    types:
      - opened
    branches:
      - 'feature/bump-react-chained-query-version-to-**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run test
